package com.maxmind.device.model

import kotlinx.serialization.Serializable

/**
 * Server-generated identifier stored locally on the device.
 *
 * This ID is generated by the MaxMind server and sent back to the client
 * for storage. It includes an HMAC signature to prevent tampering.
 * Format: "{uuid}:{hmac}"
 *
 * Similar to browser cookies/localStorage stored IDs in the JS implementation.
 *
 * @property id The stored ID string in format "{uuid}:{hmac}", or null if not yet received from server
 */
@Serializable
public data class StoredID(
    val id: String? = null,
)
